### ISSUE TITLE
【 css - 伪类 第几个元素】

### ISSUE THREAD

**Issue by GrammyLi** [GrammyLi/grammy.js#4]
```css
  <style>
    第几个
    .p:nth-child(2) {
      border: 1px solid red;
    }
   倒数第几个
    .p:nth-last-child(2) {
      border: 1px solid blue;
    }
  </style>

 
```
